apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
    image: 740580894540.dkr.ecr.us-east-1.amazonaws.com/sql_nubila_ecr:v0.1
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    - name: MYSQL_DATABASE
      value: "my_db"
  restartPolicy: Always
