apiVersion: v1
kind: Service
metadata:
  name: myapp-pod
  labels:
    app: employees
spec:
  selector:
    app: employees
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 30000
  type: NodePort
