apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: myapp-container
        image: 740580894540.dkr.ecr.us-east-1.amazonaws.com/webapp_nubila_ecr:v0.1
        ports:
        - containerPort: 8080
        env:
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "10.244.0.5"
        - name: DBUSER
          value: "root"
        - name: APP_NAME
          value: "my_app"
        - name: DATABASE
          value: "my_db"
      restartPolicy: Always
